### ISSUE TITLE
Licence grant

### ISSUE THREAD

**Issue by mcintyre321** [jcdickinson/difflib#1]
Hi I was wondering if I could have a licence grant to include your differ in my [JsonDiffPatch](https://github.com/mcintyre321/JsonDiffPatch) library? I'd like to use it to diff arrays, and I may modify it..

My project is MIT licenced and not having some of the code under a difference licence would be a big help.

**Comment by jcdickinson** [comment]
You do have my permission to change the license to MIT.

_BSD is basically the same thing as MIT so you shouldn't actually need to._

**Comment by mcintyre321** [comment]
Cheers!
